version: '2.38.2'
services:
  ath-frontend:
    container_name: ath-frontend
    build: .
    image: anityanhub-frontend:latest
    restart: always
    ports:
      - 3002:3000
    volumes:
      - ./:/ath-frontend
      - /ath-frontend/node_modules
